"""
manifest_writer.py -- small helper shared by extract_sprites.py and
render_level_map.py to build book/images/MANIFEST.md.

Each generator script writes its own JSON fragment (book/images/.manifest_<name>.json)
listing the images it produced, then calls build_manifest() to (re)assemble
MANIFEST.md from every fragment present. This lets the two scripts run in
either order, or be re-run individually, without clobbering each other's
entries.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import List

FRAGMENT_PREFIX = ".manifest_"
FRAGMENT_SUFFIX = ".json"

SECTION_ORDER = ["sprites", "levelmap"]
SECTION_TITLES = {
    "sprites": "Sprite atlas, animation, and explosion illustrations (`tools/extract_sprites.py`)",
    "levelmap": "Level-map collision/classification diagrams (`tools/render_level_map.py`)",
}


def write_fragment(out_dir: Path, name: str, entries: List[dict]) -> None:
    frag_path = out_dir / f"{FRAGMENT_PREFIX}{name}{FRAGMENT_SUFFIX}"
    frag_path.write_text(json.dumps(entries, indent=2), encoding="utf-8")


def build_manifest(out_dir: Path) -> None:
    lines = [
        "# Image manifest — `book/images/`",
        "",
        "Generated by `tools/extract_sprites.py` and `tools/render_level_map.py`. Every image "
        "listed here is either (a) a pixel-accurate crop of a real sprite atlas in "
        "`mobile-eggbert/Content/icons/`, positioned using the exact grid algorithm read from "
        "`Pixmap::GetSrcRectangle` (`Pixmap.cpp:683`), or (b) a data-driven reconstruction from "
        "real level files (`worlds/*.txt`) and the real `Is*()` collision predicates in "
        "`Decor.cpp` — never a fabricated or AI-generated image. Re-running the two scripts "
        "against a fresh `mobile-eggbert` checkout regenerates this file.",
        "",
    ]
    any_section = False
    for section in SECTION_ORDER:
        frag_path = out_dir / f"{FRAGMENT_PREFIX}{section}{FRAGMENT_SUFFIX}"
        if not frag_path.exists():
            continue
        entries = json.loads(frag_path.read_text(encoding="utf-8"))
        if not entries:
            continue
        any_section = True
        lines.append(f"## {SECTION_TITLES.get(section, section)}")
        lines.append("")
        lines.append("| File | Source data | Description |")
        lines.append("|---|---|---|")
        for e in entries:
            file_cell = f"`{e['file']}`" if e["file"] != "(none — static icon, not an animation)" else "*(none)*"
            source_cell = e["source"].replace("|", "\\|")
            desc_cell = e["desc"].replace("|", "\\|")
            lines.append(f"| {file_cell} | {source_cell} | {desc_cell} |")
        lines.append("")

    if not any_section:
        lines.append("*(no fragments found yet — run extract_sprites.py and/or render_level_map.py)*")
        lines.append("")

    lines.append("## Known gaps / honesty notes")
    lines.append("")
    lines.append(
        "- Any animation table referenced by `Decor.cpp` that this pipeline could not locate "
        "as real numeric data in `Tables.cpp` was skipped rather than guessed — look for "
        "`[object] SKIP` lines in `extract_sprites.py`'s console output on a fresh run for the "
        "current list (none were skipped as of the last run that produced this file, unless "
        "noted per-row above)."
    )
    lines.append(
        "- `table_tiplouf` (ObjectType35) is declared in `Tables.cpp` with only 3 real elements "
        "even though `Decor.cpp:8619` indexes it modulo 7 — a genuine array-bounds inconsistency "
        "in the original engine. The `object-035-small-plouf.png` sheet renders only the 3 real "
        "elements; frames 3-6 are not fabricated to paper over the gap."
    )
    lines.append(
        "- `ObjectType32`/`ObjectType33` (\"blupih\"/\"blupit\" clones) never receive an explicit "
        "`PixmapChannel` assignment inside `Decor::MoveObjectStepIcon` (unlike every other "
        "patrol-creature type in the same function). Their sheets are rendered on "
        "`PixmapChannel::Blupi` because every icon value in `table_blupih_*`/`table_blupit_*` "
        "(61-70, 237-250) falls inside `blupi.png`'s addressable range and the table names "
        "mirror the Blupi asset family — this is a reasoned inference from the data, not a "
        "located, explicit assignment; flagged here rather than presented as fully confirmed."
    )
    lines.append(
        "- `blupi1.png` is not used by any `table_blupi`-driven `BlupiAction` sequence. The only "
        "place it is genuinely used is `ObjectType201/202/203` (avatar costume skins, icons "
        "257-262, static per skin) and the first 30 frames of `ObjectType38`'s electric-arc "
        "effect (`object-038-electric-arc.png`, the one sheet in this catalog that draws from it)."
    )
    lines.append("")

    (out_dir / "MANIFEST.md").write_text("\n".join(lines), encoding="utf-8")
